import 'dart:async';

import 'package:clock/clock.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';

import 'package:mostro/core/app_routes.dart';
import 'package:mostro/core/app_theme.dart';
import 'package:mostro/core/automation/automation_id.dart';
import 'package:mostro/core/automation/automation_ids.dart';
import 'package:mostro/core/daemon_errors.dart';
import 'package:mostro/features/about/providers/mostro_node_provider.dart';
import 'package:mostro/features/order/models/invoice_rules.dart';
import 'package:mostro/features/order/providers/invoice_providers.dart';
import 'package:mostro/features/order/providers/trade_state_provider.dart';
import 'package:mostro/features/order/widgets/invoice_clock.dart';
import 'package:mostro/features/order/widgets/invoice_input_field.dart';
import 'package:mostro/features/order/widgets/invoice_widgets.dart';
import 'package:mostro/features/order/widgets/order_detail_cards.dart';
import 'package:mostro/features/settings/providers/nwc_provider.dart';
import 'package:mostro/features/settings/providers/settings_provider.dart';
import 'package:mostro/features/trades/providers/trades_providers.dart'
    show refreshTrades, tradeInfoProvider;
import 'package:mostro/l10n/app_localizations.dart';
import 'package:mostro/shared/mascot/mascot_cues.dart';
import 'package:mostro/shared/utils/reputation_age.dart';
import 'package:mostro/shared/widgets/mostro_modal.dart';
import 'package:mostro/shared/widgets/nwc_invoice_widget.dart';
import 'package:mostro/shared/widgets/peer_reputation_card.dart';
import 'package:mostro/shared/widgets/platform_aware_qr_scanner.dart';
import 'package:mostro/shared/widgets/redesign_app_bar.dart';
import 'package:mostro/src/rust/api/nostr.dart' as nostr_api;
import 'package:mostro/src/rust/api/orders.dart' as orders_api;
import 'package:mostro/src/rust/api/types.dart'
    show OrderStatus, TradeInfo, TradeUpdate;

/// Whether a trade in [status] no longer wants the buyer's invoice because it
/// moved on: the daemon took one, and the trade screen is where it continues.
///
/// `settledHoldInvoice` is not over: after a failed payout the daemon asks
/// for a new invoice while the order still reads settled — also after an
/// admin settle, which mostrod records as `settled-hold-invoice` before
/// paying, so the admin outcomes below are final. Cancellations end the step
/// too, but leave for home with their own notice
/// (`_AddLightningInvoiceScreenState._leaveIfEnded`).
bool invoiceStepIsOver(OrderStatus status) => switch (status) {
  OrderStatus.active ||
  OrderStatus.fiatSent ||
  OrderStatus.dispute ||
  OrderStatus.success ||
  OrderStatus.settledByAdmin ||
  OrderStatus.completedByAdmin => true,
  _ => false,
};

/// 13a · Receive your sats — Route `/add_invoice/:orderId`.
///
/// The buyer gives the invoice (or Lightning address) the sats are paid to.
/// One screen whether the buyer took the order or someone took theirs.
/// With NWC connected the invoice is generated by the wallet instead.
class AddLightningInvoiceScreen extends ConsumerStatefulWidget {
  const AddLightningInvoiceScreen({
    super.key,
    required this.orderId,
    this.amountSats,
    this.generateInvoice,
    this.submitInvoice,
    this.recoverState,
  });

  final String orderId;

  /// Sats amount for the invoice. `null` until the trade provider resolves it.
  final int? amountSats;

  /// Test seam forwarded to [NwcInvoiceWidget]; production leaves it null so
  /// the widget generates the invoice over NWC. See [NwcInvoiceWidget].
  @visibleForTesting
  final Future<String> Function(int amountSats)? generateInvoice;

  /// Test seam for the submission itself; production sends the invoice to
  /// the daemon through the bridge and waits for its verdict.
  @visibleForTesting
  final Future<void> Function(String orderId, String invoice, BigInt sats)?
  submitInvoice;

  /// Test seam for the state recovery after a status rejection; production
  /// runs the core's `resync()`, which replays the daemon's messages.
  @visibleForTesting
  final Future<void> Function()? recoverState;

  @override
  ConsumerState<AddLightningInvoiceScreen> createState() =>
      _AddLightningInvoiceScreenState();
}

class _AddLightningInvoiceScreenState
    extends ConsumerState<AddLightningInvoiceScreen>
    with InvoiceClock {
  /// Live validation waits this long after the last keystroke.
  static const _debounce = Duration(milliseconds: 300);

  final _invoiceController = TextEditingController();
  final _focus = FocusNode();
  bool _submitting = false;

  /// `true` while a protocol cancel is in flight — blocks re-entry and submit.
  bool _canceling = false;

  /// `true` when NWC is connected but generation failed → show manual form.
  bool _manualMode = false;

  /// One-shot guard so we don't navigate twice as further updates stream in.
  bool _navigated = false;

  /// The daemon's verdict on the last submission when it was a rejection.
  /// Kept on screen (a snackbar alone is gone in seconds) until the next
  /// submission, so the user can see why the invoice was refused and fix it.
  String? _lastError;

  /// The last submission reached the relays and the node has not answered
  /// yet (#615). Not an error: a late acceptance moves the order on and
  /// [_listenForProgress] takes the screen to the trade.
  bool _awaitingNode = false;

  /// [_awaitingNode] for over [_awaitingPatience]: a late rejection is only
  /// logged, never shown, so past this the note invites sending again.
  /// Safe either way: a late rejection consumed the pending record, and a
  /// late acceptance makes the daemon refuse the resend with a status the
  /// screen already recovers from.
  bool _awaitingLong = false;
  Timer? _awaitingTimer;
  static const _awaitingPatience = Duration(seconds: 60);

  Timer? _checkTimer;

  /// The input and trade amount [_verdict] was computed for; anything else
  /// is still pending.
  String? _verdictInput;
  int? _verdictSats;

  /// The node facts ([_NodeContext.key]) [_verdict] was judged against: the
  /// verdict is stale once the node's metadata resolves or changes.
  String? _verdictNodeKey;
  InvoiceCheck? _verdict;

  /// Fires when a valid invoice is about to stop being acceptable, so the
  /// row and the submit button follow the clock without user input.
  Timer? _expiryTimer;

  /// False once the core failed to answer: inputs go to the daemon unjudged
  /// rather than being held for a bridge that is not there.
  bool _checkerAvailable = true;

  /// Which evaluation is the current one. Bumped before each check; a reply
  /// carrying an older number is dropped, answer or failure alike.
  ///
  /// Checks overlap — the input changes, the trade amount arrives, the node's
  /// capabilities resolve — and the core answers whenever it answers, so a
  /// reply is not necessarily about what is on screen. Comparing the fields a
  /// request was built from instead means remembering to extend that
  /// comparison every time the request grows a dimension; this asks the one
  /// question those comparisons were approximating.
  ///
  /// Not to be confused with [_verdictNodeKey] and friends, which answer a
  /// different question: whether the verdict now held still fits the screen,
  /// and so whether to judge again.
  int _evaluation = 0;

  /// Whether `Paste` is offered. Only whether the clipboard holds text is
  /// asked, never its content: reading it would show the OS paste notice
  /// on every visit. On web even that asks the browser for clipboard
  /// permission, so the button is always there.
  bool _clipboardHasText = kIsWeb;

  /// Re-asks the clipboard when the buyer comes back from their wallet.
  late final AppLifecycleListener _lifecycle;

  @override
  void initState() {
    super.initState();
    _focus.addListener(() => setState(() {}));
    _lifecycle = AppLifecycleListener(onResume: _refreshClipboard);
    _refreshClipboard();
    ref.listenManual<AsyncValue<int?>>(
      invoiceDeadlineProvider(widget.orderId),
      (_, next) => trackInvoiceDeadline(next.valueOrNull),
      fireImmediately: true,
    );
    // Read as it stands, not only as it changes: an order the daemon ended
    // while this screen was closed sends it no TradeUpdate.
    ref.listenManual<AsyncValue<OrderStatus>>(
      tradeStatusProvider(widget.orderId),
      (_, next) => _leaveIfEnded(next.valueOrNull),
      fireImmediately: true,
    );
    _prefillDefaultLightningAddress();
  }

  /// Starts the field with the Lightning address saved in Settings. Only a
  /// suggestion: the buyer still presses send to agree to be paid there.
  void _prefillDefaultLightningAddress() {
    final address = normalizeInvoiceInput(
      ref.read(settingsProvider).defaultLightningAddress ?? '',
    );
    if (address.isEmpty) return;
    _setInput(address);
  }

  @override
  void dispose() {
    _checkTimer?.cancel();
    _expiryTimer?.cancel();
    _awaitingTimer?.cancel();
    _lifecycle.dispose();
    _invoiceController.dispose();
    _focus.dispose();
    super.dispose();
  }

  BigInt? _resolvedSats(WidgetRef ref) {
    final fromProvider =
        ref.watch(tradeAmountProvider(widget.orderId)).valueOrNull;
    if (fromProvider != null) return fromProvider;
    final fallback = widget.amountSats;
    return fallback != null ? BigInt.from(fallback) : null;
  }

  String get _input => normalizeInvoiceInput(_invoiceController.text);

  /// What the node's kind 38385 says the checker must know: its
  /// `lnd_networks` (an invoice for another chain is refused here rather
  /// than when the daemon tries to pay it) and its
  /// `invoice_expiration_window` (mostrod refuses an invoice with less
  /// lifetime left than this). Both may still be loading.
  _NodeContext _nodeContext() {
    final async = ref.read(mostroNodeProvider);
    // Only an answer counts, and only `AsyncData` is one. Riverpod keeps
    // handing out the previous value through both a refetch and a *failed*
    // refetch (`copyWithPrevious`, so `hasValue` survives either), and after
    // a node switch that value belongs to the node being replaced: judging
    // against it would apply the old window and network to the new node. The
    // error case is the worse of the two, because a failed fetch does not
    // resolve on its own the way a pending one does.
    //
    // A node whose capabilities never load therefore never gets a pass
    // published for it. That is the honest answer — a rule that could not run
    // did not pass — and it locks nobody out: an unjudged invoice stays
    // submittable and the daemon decides (`docs/automation-contract.md`).
    //
    // One predicate, so the facts and the flag saying they are known cannot
    // drift apart.
    final settled = !async.isLoading && !async.hasError;
    final node = settled ? async.valueOrNull : null;
    final networks =
        node?.lndNetworks
            ?.split(',')
            .map((n) => n.trim())
            .where((n) => n.isNotEmpty)
            .toList() ??
        const <String>[];
    return (
      networks: networks,
      minRemainingSecs: node?.invoiceExpirationWindow,
      key: '${networks.join(',')}|${node?.invoiceExpirationWindow}',
      factsKnown: settled,
    );
  }

  int _nowSeconds() => clock.now().millisecondsSinceEpoch ~/ 1000;

  /// When [check] stops being acceptable: `min_remaining_secs` before the
  /// invoice expires, or null when it does not expire on a known clock.
  int? _staleAt(InvoiceCheck check, _NodeContext node) {
    if (check is! InvoiceCheckValid) return null;
    final expiresAt = check.expiresAt;
    if (expiresAt == null) return null;
    return expiresAt - (node.minRemainingSecs ?? 0);
  }

  /// Retires whatever is in flight: it was asked about something the screen
  /// has moved on from.
  ///
  /// Called where a request *stops being the question*, not where its
  /// replacement starts — the two are not the same moment. An edit waits out
  /// [_debounce] before the next check begins, and a failure arriving in that
  /// gap would otherwise still hold the current number and be believed.
  void _supersede() => _evaluation++;

  void _onInputChanged() {
    _checkTimer?.cancel();
    _supersede();
    // The daemon's verdict was about the previous input; the new one gets
    // its own local verdict.
    _stopAwaiting();
    setState(() => _lastError = null);
    final input = _input;
    if (input.isEmpty) return;
    _checkTimer = Timer(_debounce, () => _evaluate(input, _resolvedSats(ref)));
  }

  /// Ask the Rust core what [input] is and whether the daemon would take it
  /// for a trade of [sats]. A core that cannot answer leaves the input to
  /// the daemon rather than refusing it for a missing bridge.
  ///
  /// Returns the verdict for *this* request, or null once it has been
  /// superseded — so a caller acting on one invoice cannot be handed the
  /// verdict of another. What it returns is the raw verdict; the node-facts
  /// withholding that [_check] applies is a readout rule and does not change
  /// whether submission is allowed.
  Future<InvoiceCheck?> _evaluate(String input, BigInt? sats) async {
    final generation = ++_evaluation;
    final node = _nodeContext();
    final request = (
      input: input,
      expectedSats: sats?.toInt(),
      nodeNetworks: node.networks,
      minRemainingSecs: node.minRemainingSecs,
      // The same clock as the countdown, so the two never disagree.
      now: _nowSeconds(),
    );
    InvoiceCheck verdict;
    try {
      verdict = await ref.read(invoiceCheckerProvider)(request);
    } catch (e) {
      debugPrint('[AddLightningInvoiceScreen] checker unavailable: $e');
      // Only the current request may declare the core unavailable. That flag
      // is sticky and short-circuits ahead of the re-judge, so an older
      // failure landing after a newer answer would blank the readout and
      // unlock submission until the buyer typed again.
      if (!mounted || generation != _evaluation) return null;
      setState(() => _checkerAvailable = false);
      // Unverified, not null: a core that cannot answer hands the input to
      // the daemon, and a caller waiting on this request must get that
      // policy rather than a refusal.
      return const InvoiceCheckUnverified();
    }
    if (!mounted || generation != _evaluation) return null;
    setState(() {
      _checkerAvailable = true;
      _verdictInput = input;
      _verdictSats = sats?.toInt();
      _verdictNodeKey = node.key;
      _verdict = verdict;
    });
    _armExpiryTimer(verdict, node);
    return verdict;
  }

  /// Re-judge a valid invoice the moment it stops being acceptable.
  void _armExpiryTimer(InvoiceCheck verdict, _NodeContext node) {
    _expiryTimer?.cancel();
    final staleAt = _staleAt(verdict, node);
    if (staleAt == null) return;
    final wait = staleAt - _nowSeconds() + 1;
    _expiryTimer = Timer(Duration(seconds: wait < 1 ? 1 : wait), () {
      if (mounted) setState(() {});
    });
  }

  /// [_check] with a fresh verdict from the core: what a submission is
  /// judged by, so a cached "valid" cannot send an invoice that expired or
  /// stopped fitting the node while the screen sat idle.
  Future<InvoiceCheck> _freshCheck(String input, BigInt? sats) async {
    _checkTimer?.cancel();
    _supersede();
    final verdict = await _evaluate(input, sats);
    if (!mounted) return const InvoiceCheckPending();
    // The verdict this request got, never whatever `_check` holds by now:
    // an edit or a node change mid-flight leaves a verdict about a different
    // invoice, and the caller would send the one it captured on the strength
    // of it. Superseded reads as pending, so nothing is sent and the buyer
    // can ask again.
    return verdict ?? const InvoiceCheckPending();
  }

  InvoiceCheck _check(BigInt? sats) {
    final input = _input;
    if (input.isEmpty) return const InvoiceCheckNone();
    if (!_checkerAvailable) return const InvoiceCheckUnverified();
    final verdict = _verdict;
    if (verdict == null || _verdictInput != input) {
      // While the core has not caught up, say nothing and hold submission.
      return const InvoiceCheckPending();
    }
    final node = _nodeContext();
    final staleAt = _staleAt(verdict, node);
    if (_verdictSats != sats?.toInt() ||
        _verdictNodeKey != node.key ||
        (staleAt != null && _nowSeconds() >= staleAt)) {
      // The verdict answered a different question — the trade amount or the
      // node's facts arrived or changed after it, or the invoice has since
      // run into the node's window: judge again, and hold submission
      // meanwhile.
      _checkTimer?.cancel();
      _supersede();
      _checkTimer = Timer(Duration.zero, () => _evaluate(input, sats));
      return const InvoiceCheckPending();
    }
    if (verdict is InvoiceCheckValid && !node.factsKnown) {
      // Two of the four rules — the expiry floor and the node's networks —
      // need facts that are still being fetched, so this pass is only the
      // absence of a failure they could not test. `valid` is a claim
      // automation reads off `invoice.check`; say nothing instead, and leave
      // it to the daemon exactly as for any invoice this side cannot judge.
      // Submission stays allowed, as it already was while claiming `valid`.
      return const InvoiceCheckUnverified();
    }
    return verdict;
  }

  bool _canSubmit(BigInt? sats) {
    if (_canceling) return false;
    final check = _check(sats);
    // A Lightning address is resolved with the trade amount, so it waits
    // for it.
    if (check is InvoiceCheckAddress && sats == null) return false;
    return invoiceCheckAllowsSubmit(check);
  }

  /// Cancel = cancel the trade itself (confirmed via dialog), not just leave
  /// the screen — going back is what lands on trade detail (#268).
  Future<void> _cancelOrder() async {
    // Serialize state-changing requests: no cancel while a submit or another
    // cancel is in flight (review round 1).
    if (_submitting || _canceling) return;
    final l10n = AppLocalizations.of(context);
    final confirmed = await showMostroDialog<bool>(
      context: context,
      builder:
          (ctx) => MostroDialog(
            title: l10n.cancelTradeDialogTitle,
            // This screen only exists before the trade goes active, where
            // mostrod cancels at once — no cooperative request.
            body: l10n.cancelTradeDialogContentNotStarted,
            secondary: ModalAction(
              label: l10n.noButtonLabel,
              onPressed: () => Navigator.pop(ctx, false),
            ),
            primary: ModalAction(
              label: l10n.yesCancelButtonLabel,
              onPressed: () => Navigator.pop(ctx, true),
              tone: ModalTone.destructive,
              automationId: AutomationIds.tradeCancelConfirm,
            ),
          ),
    );
    if (!mounted || confirmed != true) return;
    setState(() => _canceling = true);
    try {
      await orders_api.cancelOrder(orderId: widget.orderId);
      if (!mounted) return;
      _navigated = true;
      refreshTrades(ref);
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text(l10n.cancelRequestSent)));
      context.go(AppRoute.home);
    } catch (e) {
      if (!mounted) return;
      ref.read(mascotCueProvider.notifier).daemonRefused(e);
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(
            localizedDaemonError(l10n, e, fallback: l10n.cancelRequestFailed),
          ),
        ),
      );
    } finally {
      if (mounted) setState(() => _canceling = false);
    }
  }

  /// Whether the invoice went out to the daemon — accepted or refused by it.
  /// False when this side held it back: a check that refuses it, a verdict
  /// still pending, or an address waiting for the trade amount.
  Future<bool> _submit(WidgetRef ref) async {
    if (_submitting || _canceling) return false;
    final input = _input;
    // For Lightning Addresses, the sats amount must be resolved before sending —
    // the Rust side uses it to resolve the address. Bolt11 invoices encode
    // their own amount so BigInt.one is an acceptable non-zero placeholder.
    final resolvedSats = _resolvedSats(ref);
    // Judged again right now — the cached verdict may predate the trade
    // amount, the node's metadata, or the invoice's own expiry — and this
    // also guards the NWC path, which reaches here without the button.
    final check = await _freshCheck(input, resolvedSats);
    if (!mounted) return false;
    if (check is InvoiceCheckAddress && resolvedSats == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(AppLocalizations.of(context).waitingForTradeAmount),
        ),
      );
      return false;
    }
    if (!invoiceCheckAllowsSubmit(check)) {
      // The row already says why; nothing is sent.
      debugPrint('[AddLightningInvoiceScreen] invoice held back: $check');
      setState(() {});
      return false;
    }
    final sats = resolvedSats ?? BigInt.one;
    _stopAwaiting();
    setState(() {
      _submitting = true;
      _lastError = null;
    });

    try {
      final submit = widget.submitInvoice ?? _bridgeSubmit;
      await submit(widget.orderId, input, sats);
      if (mounted) ref.read(mascotCueProvider.notifier).invoiceAccepted();

      // The status listener may have left already on the same reply.
      if (!mounted || _navigated) return true;
      _navigated = true;
      context.go(AppRoute.tradeDetailPath(widget.orderId));
      return true;
    } catch (e) {
      if (!mounted) return true;
      ref.read(mascotCueProvider.notifier).daemonRefused(e);
      // sendInvoice now waits for the daemon's reply: an error means the
      // invoice was NOT accepted (CantDo, e.g. invalid invoice, or timeout),
      // so stay on this screen. Strip the Rust error prefix for readability.
      final raw = e.toString();
      final anyhowMatch = RegExp(
        r'^.*?AnyhowException\((.+)\)$',
      ).firstMatch(raw);
      final msg = anyhowMatch != null ? anyhowMatch.group(1)! : raw;
      // The daemon no longer waits for an invoice while this screen does:
      // a message was missed (typically the acknowledgement of an earlier
      // submission that outran its reply window). Ask for it again; the
      // status it carries is what takes the buyer off this screen.
      final statusRejection = isStatusRejection(msg);
      if (statusRejection) unawaited(_recoverState());
      // The answer is about the text that was sent. Edited since — the
      // field stays open while the node is waited on, up to 30 s for an
      // address — it would label the new input with the old verdict (PR #617
      // review). The status recovery above still runs: it is not about the
      // input.
      if (_input != input) return true;
      // Sent, not answered yet: the node may still accept it — an address
      // costs it an LNURL round trip — and the late reply moves the screen
      // on. Say so, without an error or a snack bar blaming the connection.
      if (msg.contains('InvoiceAwaitingDaemon')) {
        setState(() => _awaitingNode = true);
        _awaitingTimer = Timer(_awaitingPatience, () {
          if (mounted && _awaitingNode) setState(() => _awaitingLong = true);
        });
        return true;
      }
      final l10n = AppLocalizations.of(context);
      final display =
          statusRejection
              ? l10n.invoiceNoLongerExpected
              : localizedDaemonError(l10n, msg, fallback: msg);
      setState(() => _lastError = display);
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text(display)));
      return true;
    } finally {
      if (mounted) setState(() => _submitting = false);
    }
  }

  void _stopAwaiting() {
    _awaitingTimer?.cancel();
    _awaitingTimer = null;
    _awaitingNode = false;
    _awaitingLong = false;
  }

  Future<void> _recoverState() async {
    try {
      await (widget.recoverState ?? nostr_api.resync)();
    } catch (e) {
      debugPrint('[AddLightningInvoiceScreen] state recovery failed: $e');
    }
  }

  static Future<void> _bridgeSubmit(
    String orderId,
    String invoice,
    BigInt sats,
  ) => orders_api.sendInvoice(
    orderId: orderId,
    invoiceOrAddress: invoice,
    amountSats: sats,
  );

  Future<void> _refreshClipboard() async {
    if (kIsWeb) return;
    bool hasText;
    try {
      hasText = await Clipboard.hasStrings();
    } catch (e) {
      debugPrint('[AddLightningInvoiceScreen] clipboard unavailable: $e');
      hasText = false;
    }
    if (!mounted || hasText == _clipboardHasText) return;
    setState(() => _clipboardHasText = hasText);
  }

  Future<void> _paste() async {
    final data = await Clipboard.getData(Clipboard.kTextPlain);
    if (!mounted) return;
    final text = normalizeInvoiceInput(data?.text ?? '');
    if (text.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text(AppLocalizations.of(context).clipboardEmptyError),
        ),
      );
      return;
    }
    _setInput(text);
  }

  Future<void> _scan() async {
    final scanned = await Navigator.of(context).push<String>(
      MaterialPageRoute(
        builder: (routeContext) {
          final l10n = AppLocalizations.of(routeContext);
          return Scaffold(
            backgroundColor: OrderBookPalette.of(routeContext).bg,
            appBar: redesignAppBar(
              routeContext,
              title: l10n.scanQrCodeTitle,
              onBack: () => Navigator.of(routeContext).pop(),
            ),
            body: PlatformAwareQrScanner(
              hint: l10n.invoiceFieldHint,
              onDetected: (value) => Navigator.of(routeContext).pop(value),
            ),
          );
        },
      ),
    );
    if (!mounted || scanned == null) return;
    _setInput(normalizeInvoiceInput(scanned));
  }

  void _setInput(String text) {
    _invoiceController.value = TextEditingValue(
      text: text,
      selection: TextSelection.collapsed(offset: text.length),
    );
    _onInputChanged();
  }

  /// The daemon's verdict on the last refused submission, as a readout
  /// (`invoice.error`) that stays until the next submission; nothing when
  /// there is none.
  Widget? _errorReadout() {
    final error = _lastError;
    if (error == null) {
      if (!_awaitingNode) return null;
      final l10n = AppLocalizations.of(context);
      final text =
          _awaitingLong
              ? l10n.invoiceAwaitingNodeLong
              : l10n.invoiceAwaitingNode;
      return InvoiceAwaitingRow(
        text: text,
      ).withAutomationId(AutomationIds.invoiceAwaiting, label: text);
    }
    return InvoiceValidationRow(
      text: error,
      isValid: false,
    ).withAutomationId(AutomationIds.invoiceError, label: error);
  }

  /// Leave the screen when mostrod cancels the order (e.g. the buyer let the
  /// waiting-state window expire): the daemon ignores messages for a
  /// canceled order, so without this the form just sits here and every
  /// submit dies with a 10s NoDaemonResponse.
  void _listenForCancellation() {
    ref.listen<AsyncValue<TradeUpdate>>(tradeUpdatesProvider, (prev, next) {
      final update = next.valueOrNull;
      if (update == null || update.orderId != widget.orderId) return;
      if (invoiceOrderCancelled(update.status)) _leaveHome();
    });
  }

  /// Leave for home when the order's [status] says it is no longer the
  /// user's to give an invoice for. The form stays at 00:00 (#569), so this
  /// is the way out of an order that ended while the screen was closed —
  /// opened later from a notification, say: cancelled, or `pending` again
  /// once mostrod put it back in the book and wiped the trade.
  void _leaveIfEnded(OrderStatus? status) {
    if (status == null || _navigated) return;
    if (invoiceOrderCancelled(status)) {
      // Possibly from initState, where the screen cannot navigate yet.
      WidgetsBinding.instance.addPostFrameCallback((_) => _leaveHome());
    } else if (status == OrderStatus.pending) {
      unawaited(_leaveIfNoLongerTaking());
    }
  }

  /// A maker's own order reads `pending` while it is theirs, so a `pending`
  /// only ends the step once the trades confirm the user no longer takes
  /// part. Read through the bridge, not the cached list, which can lag a
  /// take that has just been saved; an unreadable store keeps the screen.
  Future<void> _leaveIfNoLongerTaking() async {
    final List<TradeInfo> trades;
    try {
      trades = await ref.read(tradeListReaderProvider)();
    } catch (e) {
      debugPrint('[AddLightningInvoiceScreen] reading the trades failed: $e');
      return;
    }
    if (participatingRole(trades, widget.orderId) == null) _leaveHome();
  }

  void _leaveHome() {
    if (_navigated || !mounted) return;
    _navigated = true;
    // The wiped trade must also disappear from the My Trades cache.
    refreshTrades(ref);
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(content: Text(AppLocalizations.of(context).orderNoLongerActive)),
    );
    context.go(AppRoute.home);
  }

  /// Leave for the trade once the order moves past the invoice step. The
  /// submission's own reply is not enough to rely on: it is awaited for 10 s,
  /// and an acknowledgement that arrives later — or is only recovered by a
  /// replay — would otherwise leave the form asking for an invoice the daemon
  /// rejects with `NotAllowedByStatus`.
  void _listenForProgress() {
    ref.listen<AsyncValue<OrderStatus>>(tradeStatusProvider(widget.orderId), (
      prev,
      next,
    ) {
      final status = next.valueOrNull;
      if (status == null || _navigated || !mounted) return;
      if (!invoiceStepIsOver(status)) return;
      _navigated = true;
      refreshTrades(ref);
      context.go(AppRoute.tradeDetailPath(widget.orderId));
    });
  }

  @override
  Widget build(BuildContext context) {
    // The verdict depends on the node's metadata: rebuild — and so re-judge
    // through `_check` — when it resolves or changes.
    ref.watch(mostroNodeProvider);
    final l10n = AppLocalizations.of(context);
    final book = OrderBookPalette.of(context);
    final isWalletConnected = ref.watch(isWalletConnectedProvider);
    final canPop = Navigator.of(context).canPop();
    final appBar = InvoiceAppBar(
      title: l10n.invoiceReceiveTitle,
      onBack: canPop ? () => Navigator.of(context).maybePop() : null,
    );

    _listenForCancellation();
    _listenForProgress();

    // Resolve sats: provider first (live polling), fall back to constructor param.
    final sats = _resolvedSats(ref);

    // Counterpart (taker) reputation: the maker is the buyer here (adding an
    // invoice), so the taker is the seller (#305). Read via tradeInfoProvider,
    // which refreshes on the TradeUpdate emitted after the snapshot persists.
    final trade = ref.watch(tradeInfoProvider(widget.orderId)).valueOrNull;

    // When NWC is connected, we need the sats amount to auto-generate an invoice.
    // Show a loading indicator only in that case. Manual entry is always available.
    if (isWalletConnected && sats == null && !_manualMode) {
      return Scaffold(
        backgroundColor: book.bg,
        appBar: appBar,
        body: _withId(
          Center(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              children: [
                const CircularProgressIndicator(),
                const SizedBox(height: AppSpacing.md),
                Text(
                  l10n.fetchingTradeAmount,
                  style: TextStyle(color: book.textSecondary),
                ),
                const SizedBox(height: AppSpacing.md),
                TextButton(
                  onPressed: () => setState(() => _manualMode = true),
                  child: Text(
                    l10n.enterInvoiceManually,
                    style: TextStyle(color: book.limeText),
                  ),
                ).withAutomationId(AutomationIds.invoiceManual),
              ],
            ),
          ),
        ),
      );
    }

    // If NWC wallet is connected, amount is known, and we haven't fallen back
    // to manual, show the auto-invoice widget instead of the manual form.
    if (isWalletConnected &&
        !_manualMode &&
        sats != null &&
        sats > BigInt.zero) {
      final error = _errorReadout();
      return Scaffold(
        backgroundColor: book.bg,
        appBar: appBar,
        body: _withId(
          Padding(
            padding: const EdgeInsets.all(AppSpacing.lg),
            child: Column(
              children: [
                // The maker must see who took their order even when NWC
                // auto-generates the invoice and the flow can proceed on its
                // own — that is exactly where the decision matters most (#305).
                if (trade?.peerRating != null) ...[
                  PeerReputationCard(
                    rating: trade!.peerRating!,
                    reviews: trade.peerReviews ?? 0,
                    days: trade.peerDaysOnMostro,
                    counterpartIsBuyer: false,
                  ),
                  const SizedBox(height: AppSpacing.lg),
                ],
                Expanded(
                  child: Center(
                    // The wallet is asked once, when the widget mounts: before
                    // the node's window is known the invoice would get the
                    // margin alone, and a node with a longer window refuses it.
                    child:
                        ref.watch(mostroNodeProvider).isLoading
                            ? const CircularProgressIndicator()
                            : NwcInvoiceWidget(
                              amountSats: sats.toInt(),
                              expirySecs: nwcInvoiceExpirySecs(
                                _nodeContext().minRemainingSecs,
                              ),
                              generateInvoice: widget.generateInvoice,
                              onInvoiceConfirmed: (invoice) async {
                                _invoiceController.text = invoice;
                                // Nothing else moves this screen on when the invoice
                                // is held back, and the widget has already stopped
                                // drawing: without the form, the screen stays blank.
                                final sent = await _submit(ref);
                                if (!sent && mounted && !_navigated) {
                                  setState(() => _manualMode = true);
                                }
                              },
                              onFallbackToManual:
                                  () => setState(() => _manualMode = true),
                            ),
                  ),
                ),
                // A generated invoice the daemon refuses needs the same
                // persistent reason as a typed one.
                if (error != null) ...[
                  const SizedBox(height: AppSpacing.md),
                  error,
                  // The readout tells the buyer to add a new invoice, but this
                  // branch has no form — its only other way out is leaving and
                  // reopening the screen, which regenerates and resubmits the
                  // wallet's (equally refused) invoice. Offer manual entry.
                  const SizedBox(height: AppSpacing.md),
                  TextButton(
                    onPressed: () => setState(() => _manualMode = true),
                    child: Text(
                      l10n.enterInvoiceManually,
                      style: TextStyle(color: book.limeText),
                    ),
                  ).withAutomationId(AutomationIds.invoiceManual),
                ],
              ],
            ),
          ),
        ),
      );
    }

    return Scaffold(
      backgroundColor: book.bg,
      // The keyboard must not cover the validation row, which sits right
      // under the field rather than in the footer.
      resizeToAvoidBottomInset: true,
      appBar: appBar,
      // The form stays at 00:00: the step ends when mostrod says so, and
      // until then it still accepts an invoice (#569).
      body: _scrollableForm(l10n, sats, trade),
    );
  }

  /// [body] under the order's ID card, for the states without the form's
  /// counterpart card (DS-CMP-22).
  Widget _withId(Widget body) => InvoiceOrderIdBody(
    orderId: widget.orderId,
    automationId: AutomationIds.invoiceOrderId,
    child: body,
  );

  Widget _scrollableForm(
    AppLocalizations l10n,
    BigInt? sats,
    TradeInfo? trade,
  ) => LayoutBuilder(
    builder:
        (context, constraints) => SingleChildScrollView(
          // #267: bottom system-bar inset so the footer clears the
          // gesture / 3-button navigation bar.
          padding: EdgeInsets.fromLTRB(
            kInvoiceGutter,
            4,
            kInvoiceGutter,
            kInvoiceGutter + MediaQuery.of(context).viewPadding.bottom,
          ),
          child: ConstrainedBox(
            constraints: BoxConstraints(
              minHeight: constraints.maxHeight - 4 - kInvoiceGutter,
            ),
            child: IntrinsicHeight(child: _form(l10n, sats, trade)),
          ),
        ),
  );

  Widget _form(AppLocalizations l10n, BigInt? sats, TradeInfo? trade) {
    final check = _check(sats);
    final error = _errorReadout();
    final validation = _validationText(l10n, check);
    return Column(
      crossAxisAlignment: CrossAxisAlignment.stretch,
      children: [
        // Sats amount calculated by the daemon (arrives in the take /
        // add-invoice reply and lands in the trade record).
        if (sats != null) ...[
          InvoiceHeroCard(
            label: l10n.invoiceYouReceiveLabel,
            sats: sats.toInt(),
            semanticsLabel: l10n.invoiceReceiveSemantics(
              formatInvoiceSats(sats.toInt(), l10n.localeName),
            ),
            contextLine: _heroContext(l10n, trade),
            automationId: AutomationIds.invoiceAmount,
            automationLabel: sats.toString(),
          ),
          const SizedBox(height: 12),
        ],
        ValueListenableBuilder<Duration?>(
          valueListenable: invoiceRemaining,
          builder:
              (context, remaining, _) =>
                  remaining == null
                      ? const SizedBox.shrink()
                      : Padding(
                        padding: const EdgeInsets.only(bottom: 12),
                        child: InvoiceTimeBand(
                          remaining: remaining,
                          window: ref.watch(invoiceStepWindowProvider),
                          sentence: l10n.invoiceTimeToSend,
                          hours: l10n.invoiceCountdownHours,
                          elapsed: stepElapsedNotice(
                            l10n,
                            buyerStep: true,
                            kind: trade?.order.kind,
                          ),
                        ),
                      ),
        ),
        InvoiceInputField(
          controller: _invoiceController,
          focusNode: _focus,
          onChanged: _onInputChanged,
          onPaste: _clipboardHasText ? _paste : null,
          onScan: _scan,
          validSats: check is InvoiceCheckValid ? check.sats : null,
          isValid: check is InvoiceCheckValid || check is InvoiceCheckAddress,
          isAddress: check is InvoiceCheckAddress,
          // A real verdict, not whatever fills the readout slot: the
          // waiting note shares it and is not an error (PR #617 review).
          hasError: _lastError != null || check is InvoiceCheckError,
        ),
        if (error != null) ...[
          const SizedBox(height: 8),
          error,
        ] else if (validation != null) ...[
          const SizedBox(height: 8),
          invoiceCheckRow(check: check, sentence: validation),
        ],
        // Always drawn: the order's ID row is in it (DS-CMP-22), and the
        // counterpart rows join once the trade loads (DS-CMP-24).
        const SizedBox(height: 12),
        OrderDataCard(
          rows: [
            if (trade != null) ..._counterpartRows(l10n, trade),
            OrderIdRow(
              orderId: widget.orderId,
              automationId: AutomationIds.invoiceOrderId,
            ),
          ],
        ),
        const Spacer(),
        const SizedBox(height: 16),
        InvoicePrimaryButton(
          icon: Icons.bolt,
          label: l10n.invoiceSendButton,
          busy: _submitting,
          onPressed: _canSubmit(sats) ? () => _submit(ref) : null,
        ).withAutomationId(AutomationIds.invoiceSubmit),
        const SizedBox(height: 4),
        InvoiceCancelLink(
          label: l10n.invoiceCancelTrade,
          // It cancels the trade, not just the screen (DS-CMP-20).
          danger: true,
          onPressed: (_submitting || _canceling) ? null : _cancelOrder,
        ).withAutomationId(AutomationIds.invoiceCancel),
      ],
    );
  }

  /// The validation row's sentence, or null when the row is not drawn.
  String? _validationText(AppLocalizations l10n, InvoiceCheck check) =>
      switch (check) {
        InvoiceCheckNone() ||
        InvoiceCheckPending() ||
        InvoiceCheckUnverified() => null,
        InvoiceCheckAddress() => l10n.invoiceValidAddress,
        InvoiceCheckValid(:final sats) => l10n.invoiceValidInvoice(
          formatInvoiceSats(sats, l10n.localeName),
        ),
        InvoiceCheckError(
          :final problem,
          :final actualMsat,
          :final expectedSats,
          :final invoiceNetwork,
          :final nodeNetwork,
          :final minRemainingSecs,
        ) =>
          switch (problem) {
            InvoiceProblem.wrongAmount => l10n.invoiceErrorWrongAmount(
              formatInvoiceMsat(actualMsat ?? 0, l10n.localeName),
              formatInvoiceSats(expectedSats ?? 0, l10n.localeName),
            ),
            InvoiceProblem.wrongNetwork => l10n.invoiceErrorWrongNetwork(
              invoiceNetwork ?? '?',
              nodeNetwork ?? '?',
            ),
            InvoiceProblem.expired => l10n.invoiceErrorExpired,
            InvoiceProblem.expiresTooSoon => l10n.invoiceErrorExpiresTooSoon(
              ((minRemainingSecs ?? 0) / 60).ceil().toString(),
            ),
            InvoiceProblem.malformed => l10n.invoiceErrorMalformed,
            InvoiceProblem.unrecognized => l10n.invoiceErrorUnrecognized,
          },
      };

  /// `≈ 312 ARS · Bitcoin Bolivia`: what the sats are worth, and the node
  /// that settles the trade (not the counterpart).
  String? _heroContext(AppLocalizations l10n, TradeInfo? trade) {
    final fiat = trade == null ? null : formatInvoiceFiat(l10n, trade);
    final node = ref.watch(activeNodeNameProvider);
    final parts = [if (fiat != null) '≈ $fiat', if (node != null) node];
    return parts.isEmpty ? null : parts.join(' · ');
  }

  List<Widget> _counterpartRows(AppLocalizations l10n, TradeInfo trade) {
    final fiat = formatInvoiceFiat(l10n, trade);
    return [
      invoiceCounterpartRow(ref, l10n, trade, l10n.invoiceSellerLabel),
      if (fiat != null)
        invoiceFiatRow(
          l10n.invoiceYouPayLabel,
          fiat,
          trade.order.paymentMethod,
        ),
    ];
  }
}

/// What the invoice checker needs from the node, plus a key that changes
/// whenever any of it does.
typedef _NodeContext =
    ({
      List<String> networks,
      int? minRemainingSecs,
      String key,
      bool factsKnown,
    });
