// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWTwMdcKyLDSe27IG-O5ZQIXe1FPRxtMs',
    appId: '1:1025036523112:web:c3fd097d34e0a392738ddd',
    messagingSenderId: '1025036523112',
    projectId: 'mostro-mexico-push',
    authDomain: 'mostro-mexico-push.firebaseapp.com',
    storageBucket: 'mostro-mexico-push.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOrsfYrkIItBLAFbnYmh4HnsxBTnT3y14',
    appId: '1:375342057498:android:5e52b9105fa36beb86e9a3',
    messagingSenderId: '375342057498',
    projectId: 'mostro-mobile',
    storageBucket: 'mostro-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXIc0i_xrVcNz_HILS2jFXUEcgbLKrfKo',
    appId: '1:375342057498:ios:a5fb156e2042607a86e9a3',
    messagingSenderId: '375342057498',
    projectId: 'mostro-mobile',
    storageBucket: 'mostro-mobile.firebasestorage.app',
    iosBundleId: 'foundation.mostro.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXIc0i_xrVcNz_HILS2jFXUEcgbLKrfKo',
    appId: '1:375342057498:ios:a5fb156e2042607a86e9a3',
    messagingSenderId: '375342057498',
    projectId: 'mostro-mobile',
    storageBucket: 'mostro-mobile.firebasestorage.app',
    iosBundleId: 'foundation.mostro.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD8h8KBxZPNr44evIa6kU2GufyeeJSwX8',
    appId: '1:375342057498:web:eebda1c22b02fe3486e9a3',
    messagingSenderId: '375342057498',
    projectId: 'mostro-mobile',
    authDomain: 'mostro-mobile.firebaseapp.com',
    storageBucket: 'mostro-mobile.firebasestorage.app',
  );
}
