// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `active_wallet`, `build_and_record_escrow`, `canonical_mint`, `changes`, `claim_legacy_store`, `current_identity`, `ensure_enabled`, `ensure_wallet_at`, `escrow_op_lock`, `forget_held_escrow`, `held_escrows`, `hold_unrecorded_escrow`, `identity_balance_at_risk`, `identity_store_name`, `install`, `legacy_store_decision`, `lifecycle_lock`, `live_wallet`, `load_trade`, `move_legacy_store`, `node_default_mint`, `notify`, `now_secs`, `offline_balance`, `open_wallet`, `proof_store_path`, `receive_unbound`, `record_escrow_token`, `recorded_or_held_escrow`, `resubmit_pending_escrows`, `retire_escrow_token`, `same_mint`, `serves`, `settle_escrow_rejection`, `settle_legacy_store`, `sibling_store_path`, `snapshot`, `store_wallet_mint`, `stored_wallet_mint`, `submit_escrow`, `validate_wallet_mint_url`, `wallet_lock`, `wallet_mint_target`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BoundWallet`, `SubmitError`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

/// Bind the wallet to a mint, unless it is already bound to it.
///
/// `mint_url` is the mint the user chose; it becomes the wallet's mint once the
/// mint has proven usable, and stays it across node switches and restarts.
/// `None` keeps the mint set before, or — on a fresh install — takes the
/// default of a Cashu node that pins exactly one ([`wallet_mint_target`]).
/// Binding another mint never deletes the proofs of the previous one: they stay
/// in the proof store and come back when the wallet is bound to it again.
///
/// Lazy by design: nothing connects at startup, so a user who never opens the
/// wallet never opens a proof store or contacts a mint.
///
/// **Errors**: `CashuNoMint` when no mint was given, set or offered,
/// `InvalidMintUrl`, `NoIdentity` before an identity is loaded,
/// `CashuNoMnemonic` for an nsec-imported identity (there is no seed to
/// derive), plus the markers from [`CashuWallet::connect`].
Future<CashuWalletStatus> cashuConnect({String? mintUrl}) =>
    RustLib.instance.api.crateApiCashuCashuConnect(mintUrl: mintUrl);

/// Current wallet status: "not connected" until the wallet is bound to a mint.
Future<CashuWalletStatus> cashuStatus() =>
    RustLib.instance.api.crateApiCashuCashuStatus();

/// Spendable balance in satoshis.
///
/// **Errors**: `CashuNotConnected`.
Future<BigInt> cashuGetBalance() =>
    RustLib.instance.api.crateApiCashuCashuGetBalance();

/// Redeem an encoded Cashu token into the wallet, returning the amount received.
///
/// An unbound wallet binds first, to the mint set before (or the node's
/// default) — and with no mint set at all, to the mint the token names. A mint
/// is adopted only by a receive that succeeds: a token that turns out spent or
/// worthless leaves the wallet unbound and nothing remembered.
///
/// **Errors**: `CashuReceiveFailed` (wrong mint, already spent, malformed),
/// `CashuTokenUnverified`, plus the markers from [`cashu_connect`].
Future<BigInt> cashuReceiveToken({required String encoded}) =>
    RustLib.instance.api.crateApiCashuCashuReceiveToken(encoded: encoded);

/// Export `amount_sats` from the wallet as an encoded token.
///
/// **Errors**: `CashuNotConnected`, `CashuAmountZero`, `CashuSendFailed`
/// (insufficient funds included).
Future<String> cashuCreateToken({required BigInt amountSats}) =>
    RustLib.instance.api.crateApiCashuCashuCreateToken(amountSats: amountSats);

/// Reconcile the proof store with the mint: proofs the mint reports spent are
/// forgotten, and the new balance is broadcast.
///
/// **Returns nothing on purpose.** It reclaims neither an unredeemed token of
/// ours nor the proofs of a half-finished send — cdk's state check cannot see
/// either — so there is no "reclaimed N sat" to report and C2 does not pretend
/// otherwise; see [`CashuWallet::sweep_spent_proofs`]. Getting an abandoned
/// token back is phase C10.
///
/// **Errors**: `CashuNotConnected`.
Future<void> cashuSweepSpentProofs() =>
    RustLib.instance.api.crateApiCashuCashuSweepSpentProofs();

/// Drop the in-memory wallet. Proofs stay on disk and the wallet's mint stays
/// set — this is a disconnect, not a wipe. A node switch does **not** call it:
/// the wallet's mint is the user's, not the node's.
Future<void> cashuDisconnect() =>
    RustLib.instance.api.crateApiCashuCashuDisconnect();

/// What the seller is about to lock, so the UI can show it before they commit.
///
/// Computed rather than taken from the daemon: the escrow request states the
/// amount but neither the mint nor the locktime, and in Cashu mode the node
/// publishes no info event that would (mostro `scheduler.rs`, "a Cashu-aware
/// info event is future work"). So the mint must be known — advertised or set
/// through the developer override — and the locktime falls back to the
/// protocol default, never to a guess.
///
/// **Errors**: `CashuNotEnabled`, `CashuOrderAmountUnknown`, `CashuMintNotSupported`,
/// `CashuWalletOnOtherMint`, `CashuNotConnected`, `CashuBalanceUnknown`, plus the
/// markers from [`cashu_connect`].
Future<CashuEscrowQuote> cashuEscrowQuote({required String orderId}) =>
    RustLib.instance.api.crateApiCashuCashuEscrowQuote(orderId: orderId);

/// Seller: fund the 2-of-3 escrow for `order_id` and submit it to the daemon.
///
/// The Cashu analogue of paying the hold invoice, built so no call can lose or
/// double-spend the seller's funds:
///
/// 1. one operation per order at a time ([`escrow_op_lock`]);
/// 2. an escrow already recorded for the trade is **re-sent as is** — the
///    daemon answers the same token with `cashu-escrow-locked` again, and a
///    different one with `invalid_cashu_token`, so a retry must never swap
///    anew;
/// 3. otherwise the balance is checked, the escrow built, and the token
///    **recorded before anything else can fail** — from the swap on, the
///    funds exist only in that token;
/// 4. the submission is correlated by `request_id` and answered by the
///    daemon: `cashu-escrow-locked`, or a `cant-do` that
///    [`settle_escrow_rejection`] turns into the next step.
///
/// **Errors** (stable markers): `CashuNotEnabled`, `CashuNotConnected`,
/// `CashuMintNotSupported`, `CashuWalletOnOtherMint`, `CashuInsufficientFunds`,
/// `NotTheSeller`,
/// `CashuEscrowOrderMovedOn`,
/// `CashuEscrowRequestMissing`, `CashuWrongTradeKey`, `DeviceClockInvalid`,
/// `CashuEscrowNotPersisted`, `CashuEscrowRejected: <reason>`,
/// `NoDaemonResponse`, plus the `CashuLockFailed` markers from construction.
Future<void> lockEscrow({required String orderId}) =>
    RustLib.instance.api.crateApiCashuLockEscrow(orderId: orderId);

/// Subscribe to wallet changes.
Future<CashuWalletStream> onCashuWalletChanged() =>
    RustLib.instance.api.crateApiCashuOnCashuWalletChanged();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<CashuWalletStream>>
abstract class CashuWalletStream implements RustOpaqueInterface {
  /// Poll for the next wallet-changed event.
  ///
  /// A lagged receiver skips dropped snapshots: the value is current state,
  /// so only the newest one matters.
  Future<CashuWalletStatus> next();
}
