// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `all`, `apply_admin_took_dispute_from`, `apply_admin_took_dispute`, `apply_admin_verdict`, `chat_key_disclosure`, `clear_dispute_keys`, `counterparty_pubkey`, `current_solver`, `cursor_is_unvouched`, `derive_admin_shared_key`, `dispute_node`, `dispute_store`, `forget_identity_disputes`, `get`, `has_dispute_keys`, `is_order_finished`, `is_peer_placeholder`, `is_stale_solver_assignment`, `new`, `note_chat_key_share_echo`, `note_peer_opened_dispute`, `note_solver_assignment`, `pending_opens`, `persist_admin_pubkey`, `persist_dispute_node`, `persist_dispute_origin`, `persist_solver_assigned_at`, `persisted_chat_key_share`, `persisted_order_is_finished`, `persisted_solver_assigned_at`, `record_chat_key_share`, `record_late_acceptance`, `recorded_solver_assignment`, `rehydrate_disputes_from_storage`, `resolve_dispute`, `resubscribe_active_dispute_chats`, `solver_assigned_at`, `solver_conversation`, `solver_pubkey`, `status_allows_dispute`, `trade_key_index`, `try_insert_if_absent_or_resolved`, `update_conditional`, `upsert_or_update`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `DisputeStore`, `PendingOpenGuard`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`

/// Initiate a dispute on an active trade.
///
/// Sends a `Dispute` action to the Mostro daemon over transport v2, waits for
/// its reply, and creates the local `Dispute` record **only** once the daemon
/// has accepted it. A publish is not an acceptance: the daemon rejects a
/// dispute the trade is not eligible for with `CantDo`, and persisting on
/// publish left that rejection unreconciled — the dispute stayed locally Open
/// forever (#202).
///
/// **Preconditions**: Trade MUST be disputable (funds in escrow). No existing
/// open dispute for this trade.
///
/// **Errors**: `TradeNotDisputable`, `DisputeAlreadyOpen`, `ProtocolError`,
/// `NoDaemonResponse`, plus daemon `CantDo` reasons passed through.
Future<Dispute> openDispute({required String tradeId, String? reason}) =>
    RustLib.instance.api.crateApiDisputesOpenDispute(
      tradeId: tradeId,
      reason: reason,
    );

/// Submit free-text evidence for an open dispute, and return it as stored.
///
/// Delivered as an admin-type message in the dispute chat.
///
/// **Errors**: `EvidenceEmpty`, `NoOpenDispute`, `AdminNotAssigned`,
/// `TradeNotFound`.
Future<ChatMessage> submitEvidence({
  required String tradeId,
  required String text,
}) => RustLib.instance.api.crateApiDisputesSubmitEvidence(
  tradeId: tradeId,
  text: text,
);

/// Send the dispute's solver the key of this trade's peer chat, so they can
/// read what buyer and seller wrote to each other (#415). It replaces copying
/// the key from the peer chat and pasting it here.
///
/// The key is `K_conv`'s secret, as v1 discloses it and as the chat spec
/// prescribes: it decrypts the conversation, but the outer events are signed
/// with `K_sign`, so it cannot write into it. Never the raw ECDH secret,
/// which derives `K_sign` too, and never `Session.shared_key`, a SHA-256 of
/// that secret from which `K_conv` cannot be derived. The trade keys are
/// this order's own, so the key opens this conversation and no other.
///
/// The message is the usual dispute chat envelope (`submit_evidence`'s path)
/// and is stored as the user's own. It counts as sent only once a relay took
/// it; then the share is persisted for the current solver.
///
/// A recorded share never refuses another: the user may have sent the key to
/// a solver who then handed the dispute over (Serbero before a human), or
/// simply want it sent again. The record only tells the screen.
///
/// **Errors**: `NoOpenDispute`, `AdminNotAssigned`, `TradeNotFound`,
/// `NoSharedKey` (the counterparty is not known), `SendFailed`.
Future<ChatMessage> shareChatKeyWithSolver({required String tradeId}) => RustLib
    .instance
    .api
    .crateApiDisputesShareChatKeyWithSolver(tradeId: tradeId);

/// Encrypt, upload and send an image or PDF to the solver (#589 phase 3).
///
/// The peer chat's `send_file`, keyed to the solver: the file key is the raw
/// ECDH between our trade key and the solver's pubkey, as v1 encrypts files
/// in the dispute chat. The solver is not a push client, so nobody is woken.
/// `on_attachment_progress(upload_id)` reports progress.
///
/// **Errors**: `FileTooLarge`, `UnsupportedFileType`, `InvalidImage`,
/// `NoOpenDispute`, `AdminNotAssigned`, `TradeNotFound`, `UploadFailed`,
/// `SendFailed`.
Future<ChatMessage> sendDisputeFile({
  required String tradeId,
  required List<int> fileBytes,
  required String fileName,
  required String uploadId,
}) => RustLib.instance.api.crateApiDisputesSendDisputeFile(
  tradeId: tradeId,
  fileBytes: fileBytes,
  fileName: fileName,
  uploadId: uploadId,
);

/// Who the solver `solver_pubkey` (hex) of `trade_id`'s dispute is, for the
/// label the dispute chat shows (#637): the assistant the dispute's own node
/// announces as its Serbero, or a person. Another node's announcement never
/// counts, and a dispute whose node is not recorded yet (assigned before the
/// app recorded it, until a replay does) shows a person. Read at display
/// time, so a label shown before the node's info event arrived corrects
/// itself on the next read.
Future<SolverRole> solverRole({
  required String tradeId,
  required String solverPubkey,
}) => RustLib.instance.api.crateApiDisputesSolverRole(
  tradeId: tradeId,
  solverPubkey: solverPubkey,
);

/// Get dispute details for a trade.
///
/// Returns `None` if no dispute exists.
Future<Dispute?> getDispute({required String tradeId}) =>
    RustLib.instance.api.crateApiDisputesGetDispute(tradeId: tradeId);

/// Handle an incoming `adminTookDispute` event.
///
/// Extracts the admin pubkey, marks the dispute as `InReview`, and derives
/// the ECDH admin shared key for dispute chat encryption. Without the event's
/// time, a solver change is always applied; the daemon path goes through
/// [`apply_admin_took_dispute`] with it.
Future<void> handleAdminTookDispute({
  required String tradeId,
  required String adminPubkey,
}) => RustLib.instance.api.crateApiDisputesHandleAdminTookDispute(
  tradeId: tradeId,
  adminPubkey: adminPubkey,
);

/// Handle an incoming `adminSettled` event (admin resolved in buyer's favour).
Future<void> handleAdminSettled({required String tradeId}) =>
    RustLib.instance.api.crateApiDisputesHandleAdminSettled(tradeId: tradeId);

/// Handle an incoming `adminCanceled` event (admin refunded the seller).
Future<void> handleAdminCanceled({required String tradeId}) =>
    RustLib.instance.api.crateApiDisputesHandleAdminCanceled(tradeId: tradeId);

/// Subscribe to dispute updates for a specific trade.
Future<DisputeStream> onDisputeUpdated({required String tradeId}) =>
    RustLib.instance.api.crateApiDisputesOnDisputeUpdated(tradeId: tradeId);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DisputeStream>>
abstract class DisputeStream implements RustOpaqueInterface {
  /// Poll for the next dispute update matching this trade.
  ///
  /// `RecvError::Lagged` does not end the stream. The skipped messages may
  /// have held this trade's latest state (its resolution), so the record as
  /// it stands now is returned in their place (PR #596 review).
  Future<Dispute> next();
}
