// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'types.dart';

// These functions are ignored because they are not marked as `pub`: `active_chats`, `add_message`, `admin_chat_context`, `advance_cursor`, `apply_reaction`, `attachment_blob`, `attachment_key_for`, `budget_ok`, `cache_attachment_blob`, `caught_up`, `chat_closed_at`, `chat_context`, `chat_grace_ends_at`, `chat_is_current`, `chat_running`, `chat_still_relevant_at`, `chat_still_relevant`, `chat_subscription_id`, `claim_chat_locked`, `claim_chat`, `claim_dispute_chat`, `clear`, `closed_by`, `connection_of`, `conversation_of`, `counterpart_of`, `cursor_key`, `ensure_durable`, `ensure_hydrated`, `eose_from`, `event_from`, `fold_held_reactions`, `forget_gone_relays`, `forget_identity_chats`, `get_messages`, `guard_key`, `hand_over_dispute_chat`, `handle_chat_event`, `handle_reaction`, `has_unsaved`, `held_floor_at`, `held_floor`, `hold_reaction`, `id_prefix`, `insert`, `is_known`, `load_chat_cursor`, `mark_as_read`, `merge_reaction`, `message_store`, `message_type`, `new`, `new`, `new`, `new`, `new`, `next_from`, `note_durability`, `notification_backlog`, `notification_candidate_now`, `notification_candidate`, `parse_chat_payload`, `peer_to_wake`, `persist_cursor`, `persisted_chat_closed`, `plausible_counterparty`, `publish_chat_payload_for`, `publish_chat_payload`, `publish_delivered_chat_payload_for`, `publish_wrapped`, `quota_exceeded`, `reacted_messages`, `reaction_allowed`, `reaction_time`, `rebuild_session`, `reject`, `relays_holding`, `release_and_close_chat`, `replace_chat_subscription_if_current`, `reset_chat_cursor`, `resubscribe_active_chats`, `run_chat_subscription`, `send_attachment`, `session_or_rebuild`, `set_download_status`, `settle_cursor`, `spawn_peer_chat`, `stop_chat_locked`, `stop_chat_subscription`, `stop_chat_subscriptions`, `store_chat_cursor_if_current`, `store_chat_cursor`, `store_outgoing_admin_message`, `subscribe_incoming_chat`, `try_take`, `unread_count_inner`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `AttachmentTarget`, `BoundedIdSet`, `ChatChannel`, `ChatContext`, `ChatRxState`, `HeldReaction`, `MessageStore`, `PublishedChat`, `ReactionOutcome`, `TokenBucket`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

/// Send an encrypted text message to the trade counterparty.
///
/// Validates that `content` is non-empty, wraps it in the chat envelope
/// (kind 14 signed with `K_sign`, inner kind 1 signed with the trade key) and
/// publishes it. If the session, peer, or relay pool is not available the
/// message is stored locally with a warning — same graceful degradation as
/// before, chat never throws for transport reasons.
///
/// Returns the sent `ChatMessage` (with `is_mine: true`).
Future<ChatMessage> sendMessage({
  required String tradeId,
  required String content,
}) => RustLib.instance.api.crateApiMessagesSendMessage(
  tradeId: tradeId,
  content: content,
);

/// React to the counterparty's message `message_id` with `emoji`, or withdraw
/// the reaction with an empty `emoji` (protocol chat.md, "Reactions").
///
/// Only a peer-chat message the counterparty wrote takes one. Unlike a
/// message, a reaction is not kept when no relay takes it — the counterparty
/// would never see it — and it wakes nobody.
///
/// Returns the message with the reaction applied; the same value reaches
/// `on_message_updated`. Errors carry a stable marker: `ReactionTooLarge`,
/// `MessageNotFound`, `ReactionNotAllowed` or `SendFailed`.
Future<ChatMessage> sendReaction({
  required String tradeId,
  required String messageId,
  required String emoji,
}) => RustLib.instance.api.crateApiMessagesSendReaction(
  tradeId: tradeId,
  messageId: messageId,
  emoji: emoji,
);

/// Get all messages for a trade, ordered by creation time (oldest first).
Future<List<ChatMessage>> getMessages({required String tradeId}) =>
    RustLib.instance.api.crateApiMessagesGetMessages(tradeId: tradeId);

/// Mark all messages in a trade as read.
///
/// Emits on the `on_unread_count_changed` stream after updating.
Future<void> markAsRead({required String tradeId}) =>
    RustLib.instance.api.crateApiMessagesMarkAsRead(tradeId: tradeId);

/// Get total unread message count across all trades.
Future<int> getUnreadCount() =>
    RustLib.instance.api.crateApiMessagesGetUnreadCount();

/// Encrypt, upload and send an image or PDF in the P2P chat (#589).
///
/// 1. Check and clean it ([`crate::attachments::media::prepare_for_send`]):
///    JPEG, PNG or PDF by content, ≤ 25 MB; images re-encoded without EXIF.
/// 2. Encrypt with the attachment key — the raw ECDH with the peer, as v1.
/// 3. Upload the blob to Blossom and keep it, still encrypted, in the cache.
/// 4. Send the v1 JSON message (`image_encrypted` / `file_encrypted`).
///
/// `upload_id` is chosen by the caller: `on_attachment_progress(upload_id)`
/// reports 0.1 prepared, 0.3 encrypted, 0.9 uploaded, 1.0 sent.
///
/// Errors are markers: `FileTooLarge`, `UnsupportedFileType`, `InvalidImage`,
/// `SessionNotFound`, `PeerUnknown`, `UploadFailed`, `SendFailed`.
Future<ChatMessage> sendFile({
  required String tradeId,
  required List<int> fileBytes,
  required String fileName,
  required String uploadId,
}) => RustLib.instance.api.crateApiMessagesSendFile(
  tradeId: tradeId,
  fileBytes: fileBytes,
  fileName: fileName,
  uploadId: uploadId,
);

/// Fetch and decrypt the attachment of `message_id` (#589).
///
/// The blob comes from the local cache, or from Blossom — verified against
/// the hash in its URL, then cached still encrypted. Decrypted in memory
/// with the key of the conversation it arrived in: the peer's for the P2P
/// chat, the solver's for the dispute chat. `on_attachment_progress(message_id)`
/// reports the download.
///
/// Errors are markers: `AttachmentNotFound`, `SessionNotFound`, `PeerUnknown`,
/// `DownloadFailed`, `DecryptionFailed`.
Future<AttachmentData> downloadAttachment({required String messageId}) =>
    RustLib.instance.api.crateApiMessagesDownloadAttachment(
      messageId: messageId,
    );

/// The web smoke test's attachment round trip (#589 phase 4): encrypt random
/// bytes, upload them to `server`, download them back, cache and decrypt
/// them. Only `test/web/smoke` calls it, against its own Blossom endpoint —
/// the app's uploads always go to the fixed server list.
///
/// Errors: `StorageUnavailable` before `init_db`, else the first step's.
Future<void> attachmentWebProbe({required String server}) =>
    RustLib.instance.api.crateApiMessagesAttachmentWebProbe(server: server);

/// Get the attachment download status for a message.
Future<DownloadStatus?> getAttachmentStatus({required String messageId}) =>
    RustLib.instance.api.crateApiMessagesGetAttachmentStatus(
      messageId: messageId,
    );

/// Stream that emits new messages for a specific trade.
Future<MessageStream> onNewMessage({required String tradeId}) =>
    RustLib.instance.api.crateApiMessagesOnNewMessage(tradeId: tradeId);

/// Incoming unread messages for notification cards, with at-least-once
/// delivery. Replays durable unread history on startup, channel lag and
/// every minute (including after resume), so a failed Dart persistence write
/// or a crash between the Rust and Dart commits is retried without a relay.
/// Consumers must deduplicate by message id, including deliberately suppressed
/// messages. Per-screen consumers want [`on_new_message`] instead.
Future<AnyMessageStream> onAnyNewMessage() =>
    RustLib.instance.api.crateApiMessagesOnAnyNewMessage();

/// Stream that emits the updated global unread count after any read/write.
Future<UnreadCountStream> onUnreadCountChanged() =>
    RustLib.instance.api.crateApiMessagesOnUnreadCountChanged();

/// Stream that emits a trade's messages again when they change after being
/// stored: a reaction to one of them, received or sent. Never a new message.
///
/// It opens with the trade's messages that carry reactions, read once it is
/// subscribed: a reaction applied between the caller's history read and the
/// subscription still arrives. A receiver that lags behind gets the same
/// snapshot again instead of a gap.
Future<MessageUpdateStream> onMessageUpdated({required String tradeId}) =>
    RustLib.instance.api.crateApiMessagesOnMessageUpdated(tradeId: tradeId);

/// Stream that emits attachment upload/download progress (0.0–1.0).
Future<AttachmentProgressStream> onAttachmentProgress({
  required String messageId,
}) => RustLib.instance.api.crateApiMessagesOnAttachmentProgress(
  messageId: messageId,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AnyMessageStream>>
abstract class AnyMessageStream implements RustOpaqueInterface {
  Future<ChatMessage?> next();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<AttachmentProgressStream>>
abstract class AttachmentProgressStream implements RustOpaqueInterface {
  Future<double?> next();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MessageStream>>
abstract class MessageStream implements RustOpaqueInterface {
  Future<ChatMessage?> next();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MessageUpdateStream>>
abstract class MessageUpdateStream implements RustOpaqueInterface {
  Future<ChatMessage?> next();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<UnreadCountStream>>
abstract class UnreadCountStream implements RustOpaqueInterface {
  Future<int?> next();
}

/// A decrypted attachment, returned by [`download_attachment`].
///
/// Handed over in memory: the plaintext never touches the disk here. Dart
/// renders it, or writes a temporary file only for an explicit "open with…".
class AttachmentData {
  final Uint8List bytes;
  final String fileName;

  /// What the bytes are, sniffed after decrypting (JPEG, PNG, PDF); for any
  /// other type, the MIME the sender declared — or `application/octet-stream`
  /// when the sender declared JPEG, PNG or PDF and the bytes are not.
  final String mimeType;

  const AttachmentData({
    required this.bytes,
    required this.fileName,
    required this.mimeType,
  });

  @override
  int get hashCode => bytes.hashCode ^ fileName.hashCode ^ mimeType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AttachmentData &&
          runtimeType == other.runtimeType &&
          bytes == other.bytes &&
          fileName == other.fileName &&
          mimeType == other.mimeType;
}
