// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `cache`, `cached_for`, `forget_identity_reputation`, `forget`, `generation`, `is_matching_user_info_reply`, `load_cache`, `new`, `reputation_from_reply`, `spawn_refresh`, `store_answer`, `store`, `with_answer`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CachedReputation`, `Store`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

/// The active node's last answer for the current identity, without asking.
///
/// `None` when that node never answered this identity, or there is no
/// identity yet.
Future<MyReputation?> cachedMyReputation() =>
    RustLib.instance.api.crateApiMyReputationCachedMyReputation();

/// Ask the active node for the user's reputation and keep the answer.
///
/// Returns the new answer, or `None` when there is none to have: full privacy
/// mode (nothing is sent), a refusal, or no reply in time. The cached answer
/// is then left as it was.
///
/// The request is signed by a throwaway key: `user-info` is read-only, so it
/// burns no trade index and links no trade key to the identity. A call made
/// while another is in flight waits for it, then asks the node itself: the
/// active node may have changed, or a rating landed, in between.
Future<MyReputation?> refreshMyReputation() =>
    RustLib.instance.api.crateApiMyReputationRefreshMyReputation();

/// Subscribe to the answers [`refresh_my_reputation`] stores.
Future<MyReputationStream> onMyReputationChanged() =>
    RustLib.instance.api.crateApiMyReputationOnMyReputationChanged();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MyReputationStream>>
abstract class MyReputationStream implements RustOpaqueInterface {
  /// The next stored answer; a lag skips ahead rather than ending the stream.
  Future<MyReputation> next();
}

/// The user's reputation as one node last reported it.
class MyReputation {
  /// The node that answered, 64-char hex.
  final String nodePubkey;

  /// Aggregated rating, the node's `total_rating`. Meaningless when
  /// [`Self::reviews`] is `0`.
  final double rating;

  /// Ratings received. `0` reads as "no reputation yet".
  final int reviews;

  /// Unix seconds of the first trade, truncated to its UTC day. `None` for
  /// an identity with no trades on this node.
  final PlatformInt64? since;

  /// Deprecated day count (`operating_days`), the fallback when the node
  /// sends no `since`.
  final int operatingDays;

  /// When this client stored the answer, unix seconds.
  final PlatformInt64 fetchedAt;

  const MyReputation({
    required this.nodePubkey,
    required this.rating,
    required this.reviews,
    this.since,
    required this.operatingDays,
    required this.fetchedAt,
  });

  @override
  int get hashCode =>
      nodePubkey.hashCode ^
      rating.hashCode ^
      reviews.hashCode ^
      since.hashCode ^
      operatingDays.hashCode ^
      fetchedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MyReputation &&
          runtimeType == other.runtimeType &&
          nodePubkey == other.nodePubkey &&
          rating == other.rating &&
          reviews == other.reviews &&
          since == other.since &&
          operatingDays == other.operatingDays &&
          fetchedAt == other.fetchedAt;
}
